version: '3.8'

name: app-euro

services:
  api:
    image: app-euro-api:1.0.0
    build:
      context: ./backend-api
      dockerfile: Dockerfile
      target: final
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development